version: 2

project_name: frontcli

changelog:
  disable: true

builds:
  - id: frontcli
    main: ./cmd/frontcli
    binary: frontcli
    ldflags: >-
      -s -w
      -X github.com/dedene/frontapp-cli/internal/cmd.version={{ .Tag }}
      -X github.com/dedene/frontapp-cli/internal/cmd.commit={{ .ShortCommit }}
      -X github.com/dedene/frontapp-cli/internal/cmd.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: frontcli_darwin
    main: ./cmd/frontcli
    binary: frontcli
    ldflags: >-
      -s -w
      -X github.com/dedene/frontapp-cli/internal/cmd.version={{ .Tag }}
      -X github.com/dedene/frontapp-cli/internal/cmd.commit={{ .ShortCommit }}
      -X github.com/dedene/frontapp-cli/internal/cmd.date={{ .Date }}
    env:
      - CGO_ENABLED=1
    targets:
      - darwin_amd64
      - darwin_arm64

archives:
  - builds:
      - frontcli
      - frontcli_darwin
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

brews:
  - repository:
      owner: dedene
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Peter Dedene
      email: peter@dedene.com
    directory: Formula
    homepage: https://github.com/dedene/frontapp-cli
    description: CLI for Front.app - manage conversations, messages, contacts, and more
    license: MIT
    install: |
      bin.install "frontcli"
    test: |
      system "#{bin}/frontcli", "--version"
